### ISSUE TITLE
Classpath quotes cause `java` process to fail on Unix systems

### ISSUE THREAD

**Issue by KettLovahr** [davidbuzatto/JJudge#2]
I was trying to get JJudge to properly run the tests on my Linux computer, but I kept coming across a Runtime Error:

![Screenshot_20240908_180357](https://github.com/user-attachments/assets/8ea7b07e-8f98-42eb-893f-5317c3d70414)

I decided to take a look at the source, and noticed that JJudge _was compiling correctly_, but for some reason, it was failing to run the `.class` file, saying that it couldn't be found.

I made a few changes to the `java` invocation on line 149 of Processor.java to pinpoint where the error was coming from, and I realized that when I removed the classpath argument, it worked.

I spent a while trying to figure out why it didn't work, but it seems to me that the problem comes from line 109 in Processor.java, quotation marks are usually interpreted by the command processor (cmd, bash, sh) to allow spaces inside a single argument, and the quotation marks are **not usually passed to the process itself**, there is a reason an array of Strings is used to invoke a process. When spawning a process through Runtime.exec, it seems that the behavior on Windows is different to that of Unix systems.

There are _literal_ quotation marks around the classpath being passed to the `java` process. That causes it to fail because it is looking for a directory with the name `"."`, quotation marks included. (Though curiously, that does not happen for `javac`, which is why it still successfully compiles the source code.)

My solution was changing the following line in Processor.java:
```java
classpathFilesWithCP = String.format( "-cp \"%s\"", classpathFiles );
```

to 

```java
classpathFilesWithCP = String.format( "-cp %s", classpathFiles );
```

But I'm sure there is a more robust solution here, especially because this will break the moment there is a space in the classpath argument.

**Comment by davidbuzatto** [comment]
@KettLovahr thanks for your contribution. It will be partially fixed in the next release. The full solution will be implemented in the next days.
